name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt install -y libsdl2-dev
      - name: Build on Linux
        run: make -j$(nproc)
  build-win:
    runs-on: arch-linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Windows Version
        run: make windows -j$(nproc)
