name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-amd64:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Deps
        run: sudo apt install -y libsdl2-dev
      - name: Build on amd64
        run: make -j$(nproc)
