name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt install -y libsdl2-dev
      - name: Build on Linux
        run: make -j$(nproc)
  build-win:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt install -y g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64 mingw-w64-tools wget
      - name: Get SDL2 devel mingw
        run: wget https://github.com/libsdl-org/SDL/releases/download/release-2.0.22/SDL2-devel-2.0.22-mingw.tar.gz && tar -xvf SDL2-devel-2.0.22-mingw.tar.gz && cd SDL2-2.0.22
      - name: Install SDL2
        run: sudo make cross
      - name: Build Windows Version
        run: make windows -j$(nproc)
